// coverage:ignore-file
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClmdo2mmTFeFIlRg4LZrXit2Q6fmKTMew',
    appId: '1:550575725276:web:ba075492058fb9bd79f219',
    messagingSenderId: '550575725276',
    projectId: 'mymeals-ef20e',
    authDomain: 'mymeals-ef20e.firebaseapp.com',
    storageBucket: 'mymeals-ef20e.appspot.com',
    measurementId: 'G-LEDXGRPZTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC96OLMoGGAwQdDJ7wxEoSjJSpzHp51wh0',
    appId: '1:550575725276:android:4005085de1dbb85c79f219',
    messagingSenderId: '550575725276',
    projectId: 'mymeals-ef20e',
    storageBucket: 'mymeals-ef20e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX6Q4l4MfE99_ca3fhue77IhiuJ3lAn2A',
    appId: '1:550575725276:ios:16f09c89cbd9e58a79f219',
    messagingSenderId: '550575725276',
    projectId: 'mymeals-ef20e',
    storageBucket: 'mymeals-ef20e.appspot.com',
    iosClientId:
        '550575725276-scdqcokfmsst44269d9aaiqltdi6pr5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.mymeals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX6Q4l4MfE99_ca3fhue77IhiuJ3lAn2A',
    appId: '1:550575725276:ios:16f09c89cbd9e58a79f219',
    messagingSenderId: '550575725276',
    projectId: 'mymeals-ef20e',
    storageBucket: 'mymeals-ef20e.appspot.com',
    iosClientId:
        '550575725276-scdqcokfmsst44269d9aaiqltdi6pr5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.mymeals',
  );
}
